### ISSUE TITLE
[Vue warn]: injection "Symbol(addLayer)" not found.

### ISSUE THREAD

**Issue by yuhongliang90** [veitbjarsch/vue-leaflet-markercluster#19]
![image](https://github.com/veitbjarsch/vue-leaflet-markercluster/assets/8544610/7e8f3d45-285c-4097-a9a6-27acb84094c8)

**Comment by veitbjarsch** [comment]
Okay. May you post some context to this problem? How shall I recreate the problem if I don't know anything about your project setup?

The best way to receive fast support here would be to create a minimal setup on codepen or some similar website which shows the error. This would give me the opportunity to look into it. 

Otherwise I could just answer:
> It works on my machine.

**Comment by veitbjarsch** [comment]
@yuhongliang90 can you please give me more information about the issue? If you don't reply I'll assume that the issue was resolved and closed the thread here.
