### ISSUE TITLE
Marker Cluster Issue: Error with Undefined Properties and Disappearing Markers on Zoom

### ISSUE THREAD

**Issue by mattiasghodsian** [veitbjarsch/vue-leaflet-markercluster#24]
I'm encountering issues with the marker cluster functionality. Specifically, I'm receiving a `Cannot read properties of undefined (reading 'lat')` error, and when zooming in or out, markers disappear. In Gothenburg there should be a cluster but nothing is there

![image](https://github.com/veitbjarsch/vue-leaflet-markercluster/assets/20265517/25528dad-13ac-4f11-a344-08a435f14bb7)

Example: https://stackblitz.com/edit/map-marker-cluster-1337

**Comment by veitbjarsch** [comment]
Hi @mattiasghodsian, thanks for you message. 

As I can see your example code have 2 problems:

1. The map prop `use-global-leaflet` must be set to `true`. The reason here is that the base markercluster plugin (this repo is only a wrapper) is only capable of using the global leaflet. Also both (the map and the markercluster) need to use the same leaflet instance. That's why this option is required to be truthy.

2. Assigning the global L need to be done before importing any vue-leaflet or the markercluster component. You can do this e.g. in the main file or just follow the following import order:
```
import L from 'leaflet';
globalThis.L = L;

import 'leaflet/dist/leaflet.css';
import 'vue-leaflet-markercluster/dist/style.css';
import { ref } from 'vue';
import { LMap } from '@vue-leaflet/vue-leaflet';
import { LMarkerClusterGroup } from 'vue-leaflet-markercluster';
```
This is important otherwise L will be undefined after bundling the resources.

After these 2 changes the plugin should work as expected.

**Comment by mattiasghodsian** [comment]
Thank you @veitbjarsch the changed made it work
