### ISSUE TITLE
LCircleMarker with LTtooltip error

### ISSUE THREAD

**Issue by or2e** [veitbjarsch/vue-leaflet-markercluster#7]
Thank you so much for your work
We have faced this problem, when using `l-circle-marker` with a nested `l-tooltip`

<details>
<summary>Error</summary>

![image](https://github.com/veitbjarsch/vue-leaflet-markercluster/assets/33551334/c95b10b2-b3e2-4438-92d6-47f2a7a10e7d)
</details>

[link to reproduce](https://stackblitz.com/edit/vitejs-vite-pjwgx4?file=src%2FApp.vue)

Current solution to the problem: set `:animate="false"`

**Comment by veitbjarsch** [comment]
Hi, thanks for the information. I'll look into it during the week. Glad to hear that you have a temporary workaround.

**Comment by veitbjarsch** [comment]
Hi, I took some time to look into your code. Unfortunately there is no perfect solution for this problem. But let's start from the beginning. This library is just a wrapper around lefalet.markercluster which extends the leaflet functionality. Leaflet.markercluster relies on the internal leaflet function _setPos, which enables them to move the marker away from the original lat/lng coordinate without touching them. This is important, because if you spiderfy the cluster you need to go back to the original values.

Unfortunately even if leaflet called the item circleMarker it has nothing to do with the leaflet marker. The circle marker is a path (leaflet marker are dom objects) and doesn't provide the option to move the drawn marker independent from the original lat/lng values. This behavior leads to the point that the circle marker can't be used within the markercluster with animation="true", because leaflet doesn't provide any way to move them around freely. 

With other words. We would need to extend the circleMarker in the leaflet repository to animate circleMarkers within the markercluster.

But there are other solutions you might could use. First one you already found out. Set animate to false, would disable the movement of the markers and the part of the code which relies on the implementation of the _setPos function. 

Another one would be to use a custom icon for the marker which displays the circle as an img/svg. This would allow you to use the leaflet marker with a circle shape.

I hope I could give you some insight how leaflet work and what is the root cause of the problem. Might be even worth of a note for the readme. So other people don't run into this issue.

**Comment by or2e** [comment]
Thanks for the detailed answer!

We are migrating the project from vue 2. There were no problems in the old project (I'll prepare a demo later)

Also, w'll try to consider workarounds.

Thank you!

**Comment by veitbjarsch** [comment]
Okay this would be helpful and interesting to see. Maybe there is a way to work around it, I didn't think of it.

**Comment by veitbjarsch** [comment]
Hey, did you had a chance to create a demo?

**Comment by or2e** [comment]
> Hey, did you had a chance to create a demo?

https://stackblitz.com/edit/vue2-vue-cli-yvpf3b?file=src%2FApp.vue

**Comment by veitbjarsch** [comment]
Thanks. This helped me to verify the source of the problem. In the  vue2 markercluster plugin the default value for       animateAddingMarkers is false. In this project our default value is set to true. If we change these settings we will receive the same result for both versions (vue 2 and vue 3). 
But you are right we should use the correct default option here. I'll address this in the upcoming release. Thanks for the information.

Nevertheless for ` :animateAddingMarkers="true"` the problem will stay the same as explained above.

**Comment by veitbjarsch** [comment]
Default behavior was adjusted in [v0.3.0](https://github.com/veitbjarsch/vue-leaflet-markercluster/releases/tag/v0.3.0)
